apiVersion: apps/v1
kind: Deployment
metadata:
  name: testedep1
  labels:
    app: teste1
spec:
  selector:
    matchLabels:
      app: teste1
  replicas: 3
  template:
    metadata:
      labels:
        app: teste1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
